import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from 'next/link'
export default function Home() {
  const content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, error explicabo. Tenetur exercitationem hic consequuntur, dolorum eaque corrupti aspernatur, at dolores aperiam repellendus sint quisquam harum officiis beatae rem quaerat."
  return (
    <div className={styles.container}>
      <script jsx>
        {`
          
        `}
      </script>
      <Head>
        <title>Coding Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h2 className={styles.title}>Welcome to Coding Blogs!</h2>
        <Image className={styles.myImg} src='/homeimg.jpg' alt='' width={201} height={132}></Image>
        <p className={styles.description}>
          A website for getting coding solutions
        </p>
        <div className={styles.homeBlogContainer}>
          <div className={styles.blogSummary}>
            <h3 className={styles.title}>This is my blog</h3>
            <p className={styles.blogp}>
              {content.substr(0,140)}....
              <Link className={styles.readMoreLink} href='/api/getblog?slug=how-to-use-flask'>Read more</Link>
            </p>
          </div>
        </div>
        
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  );
}
